
services:

  mysql:
    image: mysql:8
    container_name: game-verse-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: game_verse
      MYSQL_USER: gameuser
      MYSQL_PASSWORD: gamepass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - gameverse-net

  redis:
    image: redis:7
    container_name: game-verse-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - gameverse-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: game-verse-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/var/lib/zookeeper
    networks:
      - gameverse-net

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: game-verse-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - gameverse-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    container_name: game-verse-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - gameverse-net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.0
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - gameverse-net

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - gameverse-net

volumes:
  mysql_data:
  redis_data:
  zookeeper_data:
  kafka_data:
  es_data:

networks:
  gameverse-net:
    driver: bridge

