server:
  port: 8001

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
eureka:
  instance:
    hostname: localhost  # Override with localhost
    prefer-ip-address: true  # Register with IP instead of hostname
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
