server:
  port: 9001

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/authdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update  # Auto-create tables
    show-sql: true
  cloud:
    config:
      url: http://localhost:8000

eureka:
  instance:
    hostname: localhost  # Override with localhost
    prefer-ip-address: true  # Register with IP instead of hostname
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# env stuff
jwt:
  secret: jwt-bit-secret
  expiration-ms: 86400000